### ISSUE TITLE
Can't use ACL with phpbb groups

### ISSUE THREAD

**Issue by Valiantiam** [Eole-dev/authphpbb3#1]
Phpbb3.1

I'm trying to setup ACL to allow my global moderators to edit pages. I've tried all of the following.

![image](https://cloud.githubusercontent.com/assets/5394853/18361378/30b496c8-75c7-11e6-9dd4-2b7799968963.png)

I then have one of the people in that group try to edit on the forums and they get a permission denied / only can view page source.

**Comment by Eole-dev** [comment]
Hello,

The real name of the global moderators group is GLOBAL_MODERATORS in phpBB. However, if I remember correctly, this group is server side. It means the user's group list never contains this group. So, you can't use it directly to set permissions in DokuWiki.

A workaround could be to create a new group in phpBB and add all your global moderators to this group. Then, add this new group to the global moderator group of your phpbb installation. Finally, add this new created group to the ACLs of your DokuWiki.

If you change the group memberships in phpBB and if you use the cache feature of this plugin (phpbb_cache parameter greater than 0), you have to wait about X (value of the parameter) days in order the change is reflected. A workaround could be to temporary disable the cache by changing the value of phpbb_cache to 0.

**Comment by Valiantiam** [comment]
Sweet I will go give it a try right now. Thank you!

**Comment by Valiantiam** [comment]
How should I do users ? do they need a phpbb_USERNAME and phpbb_GROUP like that?

When I add the group and then check what the permissions are of my user - It still isn't inheriting the permissions from the group. 

![image](https://cloud.githubusercontent.com/assets/5394853/18389918/bc24f80a-766d-11e6-98b8-a5f5d2f446e1.png)

![image](https://cloud.githubusercontent.com/assets/5394853/18389941/d24e62ce-766d-11e6-9773-9ff9f5c86356.png)

**Comment by Eole-dev** [comment]
You don't need to use any prefix. By example, if you have a group in phpBB named **community_moderators** you can just use **@community_moderators** in DokuWiki to set permissions.

In your phpBB installation, your users should be members of the group **community_moderators**.

Remember to disable the cache of the DokuWiki plugin before testing.

**Comment by Valiantiam** [comment]
So to clarify, it replaces spaces in the group name with `_`

**Comment by Eole-dev** [comment]
No, I just used an example.

If your group is named **my group** in phpBB (with space), you should use **@my group** in DokuWiki.

**Comment by Valiantiam** [comment]
Got it. Thanks for all the fast responses. It's been very helpful.

**Comment by Eole-dev** [comment]
I close this issue.
Thank you.
