### ISSUE TITLE
Plugin does not work with phpBB 3.2.5

### ISSUE THREAD

**Issue by forumdigger** [Eole-dev/authphpbb3#10]
Have checked all the settings in the config manager at Dokuwiki, the path is correct and the auth type is set. But Dokuwiki throws a lot of errors and says that authentication is not possible.

Any ideas, is this plugin still under development?

**Comment by Eole-dev** [comment]
I just tested with the latest versions of DokuWiki and phpBB and the plugin works. Also, for information, I updated it today.

Maybe it's a configuration issue. What is the error displayed?

**Comment by forumdigger** [comment]
After a lot of checking and testing I finally found the reason. The errors Dokuwiki was throwing were somehow misleading, several lines telling me that there is an authorization error. But in one line it says there is a configuration error.
So I activated debug logging in Dokuwiki and it says that the config option dbhost is missing. I looked around and the only config option with this name can be found in the phpBB config file. And yes, the option dbhost was empty. The forum runs, nevertheless.
With a filled option (localhost) in place the bridge now runs pretty well. Thanks a lot for this nice piece of work and for answering!

**Comment by Eole-dev** [comment]
I'll update the plugin to handle this (empty dbhost).
Thank you for your feedback.

**Comment by forumdigger** [comment]
Ok, thanks a lot!
________________________________
Von: Eole <notifications@github.com>
Gesendet: Donnerstag, 17. Januar 2019 13:37
An: Eole-dev/authphpbb3
Cc: forumdigger; Author
Betreff: Re: [Eole-dev/authphpbb3] Plugin does not work with phpBB 3.2.5 (#10)


I'll update the plugin to handle this (empty dbhost).
