### ISSUE TITLE
Fatal Error Message

### ISSUE THREAD

**Issue by mikepardon** [Eole-dev/authphpbb3#5]
I'm getting an error on several pages whilst using the plugin:

Fatal error: Call to undefined method DokuWiki_Auth_Plugin::__destruct() in /var/sites/m/moes-throwdown.com/public_html/lib/plugins/authphpbb3/auth.php on line 92

This comes up, sometimes (it seems) at random, but it also comes up when using the media section to upload new images, and it's restricting me.

My Site: [http://moes-throwdown.com/](http://moes-throwdown.com/)

**Comment by Eole-dev** [comment]
Hi,

Thank you for your report.

I published a new version which should fix this issue.
